"""ranks table

Revision ID: 591faf7a0df0
Revises: 2ca55d736ac8
Create Date: 2024-03-22 17:36:59.979147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591faf7a0df0'
down_revision: Union[str, None] = '2ca55d736ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.Column('rank_name', sa.String(), nullable=False),
    sa.Column('rank_nato_equiv', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rank_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rank')
    # ### end Alembic commands ###
